### PR TITLE
Republic Modifications

### PR DESCRIPTION
**Pull request by stackpoint**
Adjust skill allocation
 Tighten Lottery Leader Skills

### CODE REVIEW

**Comment by SpiritBaker** [comment]
100years
looks good in general

**Comment by SpiritBaker** [comment]
130years


Nvm I forgot to grab scripted effect Still kinda funny.

**Comment by SpiritBaker** [comment]
no_candidate
candidate options don't work, AI stuck with  111 immortal leader

**Comment by SpiritBaker** [comment]
So I re-elected my first candidate couple of times, I'm waiting a month and firing event and again, every candidate option is fixed 411.  Repeated it a dozen of times still getting fixed  411 candidates. 
Also the monarch point reward for every re-election is a bit too much. It basically 1 points per month * 12 * 4 year average election cycle = 48. Even tho u can get decent rulers as republic rtn.

**Comment by stackpoint** [comment]
Was testing a bit and a side effect of fixing the skill distribution is that there are a lot fewer 6/6/6 rulers.

**Review by SpiritBaker — APPROVED** [review]

**Pull request merged**
