### PR TITLE
Republic Modifications

### PR DESCRIPTION
**Pull request by stackpoint**
See: https://github.com/SpiritBaker/Difficulty-and-AI/issues/6

- Scale Reelection Cost
- Tradition stability event
- AI Reelection Improvements
- Vary Republican Leaders

### CODE REVIEW

**Comment by SpiritBaker** [comment]
I'll start new game with this and new fort  upgrade decision

**Comment by SpiritBaker** [comment]
I think random skills are fairly limited. Average total monarch point would be at less than 9, which is like 3 3 3 ruler. I think there is still only one dominant strategy, and it's to game the system. 
So my suggestion is to make every candidate to average at 9 and above. With slight random attribute bonus scaled from ur current Republic tradition.  For example +3 at 90 and above, +2 at 75 and above and +1 at 60 and above. 
And limit reelection bonus to 1-2 random skill, to compensate for average increase  in monarch points.

This way u have a choice, u can still game the system if u get really good candidate and reelect him over and over. Or u can keep republic tradition at around 90ish.

**Comment by stackpoint** [comment]
> So my suggestion is to make every candidate to average at 9 and above.

Well the random spread 0-2/3-5 was the reflect vanilla's 1/4 (6 total) spread. We can increase it to a 1-3/4-6 spread and that would be a strict upgrade over vanilla (6-12 total).

> With slight random attribute bonus scaled from ur current Republic tradition. For example +3 at 90 and above, +2 at 75 and above and +1 at 60 and above.

I don't think this works for gameplay reasons. If having high tradition grants strong rulers then there would be no point in reelecting and having tradition drop. I think the abstraction of tradition is that there is supposed to be strong incentives to reelections (+skills) and having high tradition shouldn't be making better rulers. That dominant strategy is basically the way republics are supposed to be played.

**Comment by SpiritBaker** [comment]
image
Found a couple of 666 rulers, upd 3 tags with 666 and one with 665
And the distribution is skewed towards one skill, there is a lot of rulers with 6 in one category.  We should probably limit main random skill to 5 instead of 6.

**Comment by stackpoint** [comment]
1-3 minor; 4-5 major skills?

**Review by SpiritBaker — APPROVED** [review]
It looks good so far. Not sure how strong republics can be now in a hands of the player. But we can adjust it if it's too strong.

**Pull request merged**
