### PR TITLE
Upgrade Forts Decision

### PR DESCRIPTION
**Pull request by stackpoint**
Fort decision for AI to make upgrades in timely fashion.

### CODE REVIEW

**Comment by stackpoint** [comment]
I did notice the AI building forts more often with the new patch but I did notice some gaps too. I'll run a couple games to gather data.


All the chances the AI had to click the button on the first of the year: [possible forts](https://github.com/SpiritBaker/Difficulty-and-AI/files/4946329/new.2.txt)

**Comment by SpiritBaker** [comment]
Settings for fort upgrades are not very effective. So decision can work.

**Comment by SpiritBaker** [comment]
With current settings I only have one problem with large Empires, due to how much stuff AI needs to build. And fort upgrades have relatively low priority.

**Comment by stackpoint** [comment]
We can lower the financial priority of the forts by increasing the monetary conditional:
```
ROOT = {
	treasury = 300
	current_income_balance = 3
}
```
This is the current single fort upgrade buffer. Any suggestions?

**Comment by SpiritBaker** [comment]
I'm adding it to my local copy. Will test it tomorrow.

**Comment by SpiritBaker** [comment]
It needs to factor num of loans. I'm looking at Persia with 10+loans but with pretty good income. Instead of repaying loans AI upgrades forts.

**Comment by SpiritBaker** [comment]
well, he also builds manufactories on his own

**Comment by SpiritBaker** [comment]
I guess I can add num of loans = 1 as a condition to every existing building, to fix this problem more or less completely.

**Comment by stackpoint** [comment]
Added loan and eco check.

**Comment by SpiritBaker** [comment]
I'm seeing a lot fort clusters, in HRE or any place with a bunch of opms. 

Eco check needs be a bit tighter.
For example, it triggered for Brunswick. But he should be building manufactories. 
[1567.11.18]:Brunswick fort_16th Braunschweig 

image

**Comment by stackpoint** [comment]
Are manufactories the only buildings the AI should build first?

**Comment by SpiritBaker** [comment]
It's the most expensive eco building AI can build. ~400-500
I don't think adding condition for manufactories will work. I lowered priority for certain manufactories depending on a trade good, to leave a room for soldiers household.

**Comment by stackpoint** [comment]
Should I set it so they have to build a manufactory in every owned province they can before upgrading any forts or just in that specific province that they want to upgrade the fort in?

**Comment by SpiritBaker** [comment]
`root_can_build_manufactory_here_trigger = no`
w8 a sec how I missed that, tho it's limited to only old manufactories

I still dont think it will work, and can actually cause problems. We can just adjust eco buffer to ~600 ducats.

**Comment by SpiritBaker** [comment]
image
Fort density I mentioned earlier

**Comment by stackpoint** [comment]
The decision only builds new forts in the capital so this clumping is a HRE conquest specific problem. Though, I can make a fort delete decision based on consecutive forts or total development.

**Comment by SpiritBaker** [comment]
Well we have two sources for building forts in a capital, that's a part of problem. Building logic for 15th forts still works, only logic for upgrades are ineffective. 
Also decision for deleting Forts might not work as intended, especially in hre where is alot of development. But it will give some control over the fort distribucion.

**Review by SpiritBaker — APPROVED** [review]

**Pull request merged**
