### PR TITLE
Japan fixes and improvements

### PR DESCRIPTION
**Pull request by Svatopluk1**
- Fix the subject type of event-released Japanese Shogunate tags.
- Ensure the United Shogunate government type does not lose Japan-specific mechanics, such as samurai.
- Allow a dismantled Empire of China to be restored if a country meets all requirements for claiming the Mandate via decision.

For further comments on the why and how, check the extended descriptions of the individual commits.

### CODE REVIEW

**Comment by SpiritBaker** [comment]
To my knowledge restoring Empire of China wasn't actually possible. If you could test this and confirm that it could work I will give it a go. The rest looks good.

**Comment by Svatopluk1** [comment]
"dismantle_empire_of_china = no" works, surprisingly. Tested by console-fullannexing Ming as Oirat: EoC got dismantled, then with this adjusted decision it could be recreated.

-----

The way Japan works in vanilla is that the shogunate government reform enables samurai and shogunate_mechanic (Sankin Kotai, etc). With the vanilla unite_japan decision, the shogunate gov reform is abolished but at the same time the newly formed united Japan gets a country modifier that gives it samurai; simultaneously, it loses shogunate_mechanic, which makes sense as there are no more daimyo tags at the time (a requirement for taking the decision).

In this mod it looks like united_shogunate is supposed to be an intermediate step between the vanilla shogunate and a fully united Japan, in the sense that you get the gov reform _before_ fully uniting Japan. The issue is that united_shogunate does not grant samurai nor shogunate_mechanic. So the stages you'd go through with this mod without this patch are:
1. Shogunate. Has samurai, daimyo, and daimyo-interactions like Sword Hunt, etc. (same as vanilla)
2. United Shogunate. Does _not_ have samurai, but has some daimyo, but does _not_ have daimyo-interactions. (_this is the issue_)
3. United Japan. Has samurai again, no daimyo, no daimyo-interactions. (similar to vanilla, but with a unique gov reform)

With this patch, you have samurai in all 3 stages, daimyo-interactions in stages 1 and 2 (that's when you still have daimyos, so that makes sense), and the unique intermediate government form in stage 2. Having (another) unique government form in stage 3 might be even more flavorful, but that's something possibly for later. This patch simply fixes the issue with stage 2.

**Comment by Svatopluk1** [comment]
Also, a minor point: the unite_japan_mission, while using this mod, generally provides no reward. The reason for that is that the unite_japan decision (which gives the mod's reformed united_shogunate) is both easier to fulfill _and_ provides a stronger reward than the mission.

- unite_japan decision. Requirements: own most of Japan. Reward: permaclaim on all of Japan, including Okinawa.
- unite_japan_mission. Requirements: own all of Japan except Okinawa. Reward: permaclaim on Okinawa.

**Comment by SpiritBaker** [comment]
It's great to hear that Empire of China could be resored. 
The units part, I have no objections here. The United Shogunate should have samurai special units. Since I've not played the game for the past year and half, it's something that I just missed while updating.
The idea behind United shogunate is to represent the Tokugawa shogunate. It felt kinda weird that the game lets you skip shogunate completely while historically it only ceased to exist in 19 century.

**Pull request merged**
